# Generated by Django 3.1.7 on 2021-03-24 00:08

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome_completo', models.CharField(blank=True, max_length=60, verbose_name='Nome Completo:')),
                ('idade', models.CharField(blank=True, max_length=15, verbose_name='Idade:')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo:')),
                ('situacao', models.CharField(blank=True, max_length=20, verbose_name='Situação:')),
                ('niver', models.CharField(blank=True, max_length=30, verbose_name='Data de Aniversário:')),
                ('conversao', models.CharField(blank=True, max_length=30, verbose_name='Data de Conversão:')),
                ('batismo', models.CharField(blank=True, max_length=30, verbose_name='Data de Batismo:')),
                ('Localizacao', models.CharField(blank=True, max_length=200, verbose_name='Endereço:')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone:')),
                ('foto', models.ImageField(default='/static/midia/10.png', upload_to='D:/', verbose_name='Foto')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='iuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=60, verbose_name='Nome Completo:')),
                ('idadi', models.CharField(blank=True, max_length=15, verbose_name='Idade:')),
                ('ocupacao', models.CharField(blank=True, max_length=100, verbose_name='Cargo:')),
                ('estado', models.CharField(blank=True, max_length=20, verbose_name='Situação:')),
                ('aniversario', models.CharField(blank=True, max_length=30, verbose_name='Data de Aniversário:')),
                ('convert', models.CharField(blank=True, max_length=30, verbose_name='Data de Conversão:')),
                ('banho', models.CharField(blank=True, max_length=30, verbose_name='Data de Batismo:')),
                ('casa', models.CharField(blank=True, max_length=200, verbose_name='Endereço:')),
                ('tel', models.CharField(blank=True, max_length=30, verbose_name='Telefone:')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
