# Generated by Django 3.1.7 on 2021-02-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='static/midia/10.png', upload_to='D:/', verbose_name='Foto'),
        ),
    ]
