# Generated by Django 3.1.7 on 2021-04-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_dizimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='relatorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_rela', models.CharField(blank=True, max_length=100, verbose_name='Nome do Relatorio:')),
                ('relatorio', models.TextField(blank=True, max_length=900, verbose_name='Relatório:')),
                ('data_relatorio', models.CharField(blank=True, max_length=50, verbose_name='Data do Relatorio:')),
            ],
        ),
    ]
