# Generated by Django 3.1.7 on 2021-11-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_relatorios'),
    ]

    operations = [
        migrations.CreateModel(
            name='estatuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatuto', models.TextField(blank=True, max_length=1000000, null=True, verbose_name='Artigos')),
                ('estatuto_data', models.CharField(blank=True, max_length=100, null=True, verbose_name='Data Estatuto')),
            ],
        ),
    ]
